c23/TaskUploader/config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :comments
  resources :solutions, :has_many => :comments
  resources :tasks, :has_many => :comments

  mount Sidekiq::Web => '/jobs' 
end

c23/TaskUploader/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, :polymorphic => true
end

c23/TaskUploader/app/models/solution.rb
class Solution < ActiveRecord::Base
	validates :task_id, presence: true
	validates :code, presence: true
	validates :author, presence: true

	has_many :comments, :as => :commentable
end

c23/TaskUploader/app/models/task.rb
class Task < ActiveRecord::Base
  validates :title, presence: true
  validates :description, presence: true
  validates :tests, presence: true

  has_many :comments, :as => :commentable
end

c23/TaskUploader/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

c23/TaskUploader/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @commentable = find_commentable
    @comments = @commentable.comments
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @commentable = find_commentable
    @comment = @commentable.comments.build(params[:comment])
    if @comment.save
      flash[:notice] = "Successfully created comment."
      redirect_to :id => nil
    else
      render :action => 'new'
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def find_commentable
      params.each do |name, value|
        if name =~ /(.+)_id$/
          return $1.classify.constantize.find(value)
        end
      end
      nil
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :commentable_id, :commentable_type)
    end
end

c23/TaskUploader/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      redirect_to action: :show
    else
      render action: :new
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])

    if @task.update_attributes(task_params)
      redirect_to action: :show
    else
      render action: :edit
    end
  end

  private

  def task_params
    params.require(:task)
      .permit(:title, :description, :tests)
  end
end

c23/TaskUploader/app/helpers/application_helper.rb
module ApplicationHelper
end

c23/TaskUploader/app/helpers/comments_helper.rb
module CommentsHelper
end

c23/TaskUploader/app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :commentable_id %><br>
    <%= f.number_field :commentable_id %>
  </div>
  <div class="field">
    <%= f.label :commentable_type %><br>
    <%= f.text_field :commentable_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

c23/TaskUploader/app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

c23/TaskUploader/app/views/comments/index.html.erb
<div id="comments">
<% for comment in @comments %>
  <div class="comment">
    <%=simple_format comment.content %>
  </div>
<% end %>
</div>


<h2>New Comment</h2>

<% form_for [@commentable, Comment.new] do |f| %>
  <p>
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

c23/TaskUploader/app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

c23/TaskUploader/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>Commentable:</strong>
  <%= @comment.commentable_id %>
</p>

<p>
  <strong>Commentable type:</strong>
  <%= @comment.commentable_type %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

c23/TaskUploader/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskUploader</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

c23/TaskUploader/app/views/tasks/_form.html.erb
<style>label { display: block; }</style>

<%= form_for @task do |f| %>
  <% if @task.errors.present? %>
    <ul>
      <% @task.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.label :tests %>
    <%= f.text_area :tests %>
  </div>

  <%= f.submit %>
<% end %>

c23/TaskUploader/app/views/tasks/edit.html.erb
<h1><%= t('.edit_task') %></h1>

<%= render 'form' %>

c23/TaskUploader/app/views/tasks/index.html.erb
<h1><%= t('.all_tasks') %></h1>

<% @tasks.each_with_index do |task, i| %>
  <h2>
  <%= link_to t('.title',
                index: i+1,
                title: task.title
               ),
                task_path(task)
              %>
  </h2>
<% end %>

c23/TaskUploader/app/views/tasks/new.html.erb
<h1><%= t('.create_task') %></h1>

<%= render 'form' %>

c23/TaskUploader/app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<pre>
  <%= @task.description %>
</pre>

<pre>
  <%= @task.tests %>
</pre>